---
- name: Onboarding play
  hosts: danaservers
  vars_files: variables.yaml
  tasks:
   - name: Create a file
     ansible.builtin.copy:
      dest: "{{ file_to_add.name }}"
      content: "{{ file_to_add.content }}"
      mode: "0754"
   - name: Extract IP and MAC addresses
     ansible.builtin.lineinfile:
      line: " {{ item }} | {{ ansible_facts[item]['ipv4']['address'] | default('N/A') }} | {{ ansible_facts[item]['macaddress'] | default('N/A') }}"
      dest: output-{{ inventory_hostname }}.txt
      state: present
      create: true
      insertafter: EOF
      mode: "0754"
     with_items:
      - "NAME | IP | MAC "
      - "{{ ansible_interfaces }}"
   - name: Copy network info
     ansible.builtin.command: cat output-{{ inventory_hostname }}.txt
     register: network_output
   - name: Copy file content
     ansible.builtin.command: cat ./dvir-ansible.txt
     register: command_output
   - name: Print command output
     ansible.builtin.debug:
      msg: "{{ network_output.stdout }}"
   - name: Install packages
     become: true
     ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
     with_items:
      - "{{ packages }}"
   - name: Delete files
     ansible.builtin.file:
      path: "{{ item }}"
      state: absent
     with_items:
      - "output-{{ inventory_hostname }}.txt"
      - "{{ file_to_add.name }}"
